# Generated by Django 2.2 on 2020-12-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car', models.CharField(max_length=256)),
                ('queue_number', models.IntegerField()),
                ('registration', models.DateTimeField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Auto_service')),
            ],
        ),
        migrations.CreateModel(
            name='Clients_queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField()),
                ('done_date', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Auto_service')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Task')),
            ],
            options={
                'ordering': ['service__duration', 'task__registration'],
            },
        ),
    ]
