# Generated by Django 2.2 on 2020-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_queue',
            name='done_date',
            field=models.DateTimeField(null=True),
        ),
    ]
