# Generated by Django 2.2 on 2020-12-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201205_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients_queue',
            name='at_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients_queue',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
