# Generated by Django 2.2 on 2020-12-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201205_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_service',
            name='workplaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auto_service',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='queue_number',
            field=models.IntegerField(default=0),
        ),
    ]
