# Generated by Django 2.2 on 2020-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20201205_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients_queue',
            name='is_next',
            field=models.BooleanField(default=False),
        ),
    ]
